# Generated by Django 5.0.3 on 2024-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0002_alter_room_room_type_alter_profile_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Icon svg format'),
        ),
    ]
