# Generated by Django 5.0.3 on 2024-04-27 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0003_comment_delete_ratinglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
    ]
