# Generated by Django 5.0.6 on 2024-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0003_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
