# Generated by Django 5.0.3 on 2024-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0004_image_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate_to_uzs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
