# Generated by Django 5.0.3 on 2024-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0005_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_pets',
            field=models.BooleanField(default=False, verbose_name='Pets are allowed'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(verbose_name='Check in'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(verbose_name='Check out'),
        ),
    ]
