# Generated by Django 5.0.3 on 2024-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0006_room_is_pets_alter_room_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currency',
            field=models.CharField(default='UZS', max_length=3, verbose_name='currency'),
        ),
    ]
