# Generated by Django 5.0.3 on 2024-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0008_remove_exchangerate_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='from_currency',
            field=models.CharField(max_length=3, verbose_name='from_currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='to_currency',
            field=models.CharField(max_length=3, verbose_name='to_currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
    ]
