# Generated by Django 5.0.3 on 2024-07-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0009_alter_exchangerate_from_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
