# Generated by Django 5.0.3 on 2024-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houze', '0010_delete_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='from_currency')),
                ('to_currency', models.CharField(max_length=3, verbose_name='to_currency')),
                ('value', models.FloatField(verbose_name='Value')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
