# Generated by Django 5.0.3 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0003_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='Buyer', max_length=6, verbose_name='Buyer or Seller'),
        ),
    ]
