# Generated by Django 5.0.3 on 2024-07-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0006_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previously_seller',
            field=models.BooleanField(default=False, verbose_name='Previously seller'),
        ),
    ]
