# Generated by Django 5.0.3 on 2024-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0007_profile_previously_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
    ]
