# Generated by Django 5.0.3 on 2024-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0008_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(default='English', max_length=255, verbose_name='Languages'),
        ),
    ]
