# Generated by Django 5.0.3 on 2024-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0010_alter_profile_languages_alter_room_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='checkin_time',
            field=models.TimeField(default='10:00', verbose_name='Check in time'),
        ),
        migrations.AddField(
            model_name='room',
            name='checkout_time',
            field=models.TimeField(default='23:00', verbose_name='Check out time'),
        ),
    ]
