# Generated by Django 5.0.3 on 2024-07-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('houz', '0011_room_checkin_time_room_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='country',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
