# Generated by Django 5.0.3 on 2024-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houz', '0012_room_country_alter_room_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_pets',
        ),
        migrations.AddField(
            model_name='room',
            name='pets',
            field=models.IntegerField(default=0, verbose_name='Pets'),
            preserve_default=False,
        ),
    ]
