# Generated by Django 5.0.2 on 2024-03-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0002_alter_rating_options_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
