# Generated by Django 5.0.2 on 2024-02-25 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0002_remove_room_facilities_delete_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review_text',
            field=models.TextField(verbose_name='Review text'),
        ),
    ]
