# Generated by Django 5.0.2 on 2024-02-25 20:39

import django.core.validators
import uzrent.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0003_alter_rating_rating_alter_rating_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=uzrent.models.RangedIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
