# Generated by Django 5.0.2 on 2024-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='brief_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
