# Generated by Django 5.0.2 on 2024-03-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0004_chat_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
