# Generated by Django 5.0.2 on 2024-03-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0006_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='User',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
