# Generated by Django 5.0.2 on 2024-02-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
