# Generated by Django 5.0.3 on 2024-03-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
