# Generated by Django 5.0.3 on 2024-03-20 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0010_remove_notification_user_notification_reciever_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uzrent.room'),
            preserve_default=False,
        ),
    ]
