# Generated by Django 5.0.3 on 2024-03-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0013_remove_usernotifications_reciever_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
