# Generated by Django 5.0.3 on 2024-03-24 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0014_alter_notifications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
