# Generated by Django 5.0.3 on 2024-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0016_notifications_check_in_notifications_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
