# Generated by Django 5.0.3 on 2024-03-25 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0017_notifications_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomSave',
            new_name='Bookmark',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check in')),
                ('check_out', models.DateField(verbose_name='Check out')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzrent.room')),
            ],
        ),
    ]
