# Generated by Django 5.0.2 on 2024-03-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0018_rename_roomsave_bookmark_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='room_id',
            new_name='room',
        ),
    ]
