# Generated by Django 5.0.3 on 2024-04-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0022_booking_created_at'),
        ('uzrent', '0022_booking_created_at_booking_user'),
    ]

    operations = [
    ]
