# Generated by Django 5.0.3 on 2024-04-17 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0024_alter_booking_created_at_alter_bookmark_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
