# Generated by Django 5.0.3 on 2024-04-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0026_rename_notifications_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='brief_name',
            new_name='title',
        ),
    ]
