# Generated by Django 5.0.3 on 2024-04-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0027_rename_brief_name_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='room/photos'),
        ),
    ]
