# Generated by Django 5.0.3 on 2024-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0028_alter_photo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='room/images')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, to='uzrent.image'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
