# Generated by Django 5.0.3 on 2024-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0029_image_room_images_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='room/images'),
        ),
    ]
