# Generated by Django 5.0.3 on 2024-04-23 01:51

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzrent', '0030_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=255),
        ),
    ]
